// Phase 1-4 Lesson Data
const PHASES_1_4 = [
    {
        id: 'p1', title: 'Phase 1 — Programming Mindset', lessons: [
            {
                id: 'p1l1', title: 'Computational Thinking',
                en: 'Programming is much more than just typing code; it is a way of thinking! We call this <strong>"Computational Thinking."</strong> Think of it as a set of mental tools that help you solve any problem, even if you are not at a computer.<br><br>It has 4 pillars:<br>\n<div class="feature-grid">\n  <div class="feature-card"><span class="f-icon">🧩</span><h5>Decomposition</h5><p>Breaking a big task (like "Cleaning a Room") into smaller, manageable tasks like "making the bed" and "sweeping the floor."</p></div>\n  <div class="feature-card"><span class="f-icon">🔍</span><h5>Pattern Recognition</h5><p>Noticing similarities, like how making a sandwich is similar to making a burger—both need bread and fillings.</p></div>\n  <div class="feature-card"><span class="f-icon">💡</span><h5>Abstraction</h5><p>Focusing on what matters. When driving, you need to know the steering wheel, not the internal engine valves.</p></div>\n  <div class="feature-card"><span class="f-icon">📝</span><h5>Algorithms</h5><p>Creating a specific, step-by-step list of instructions (a recipe) for someone or a computer to follow.</p></div>\n</div>',
                ar: 'البرمجة هي أكثر من مجرد كتابة أكواد؛ إنها طريقة تفكير! نسمي هذا <strong>"التفكير الحاسوبي"</strong>. فكر فيه كمجموعة من الأدوات الذهنية التي تساعدك على حل أي مشكلة، حتى لو لم تكن أمام الكمبيوتر. يتكون من 4 ركائز:<br>\n<div class="feature-grid">\n  <div class="feature-card"><span class="f-icon">🧩</span><h5>التفكيك (Decomposition)</h5><p>تقسيم مهمة كبيرة (مثل "تنظيف الغرفة") إلى مهام أصغر وأسهل مثل "ترتيب السرير" و "كنس الأرضية".</p></div>\n  <div class="feature-card"><span class="f-icon">🔍</span><h5>التعرف على الأنماط</h5><p>ملاحظة التشابهات، مثل كيف أن صنع ساندويتش مشابه لصنع برجر — كلاهما يحتاج إلى خبز وحشوات.</p></div>\n  <div class="feature-card"><span class="f-icon">💡</span><h5>التجريد (Abstraction)</h5><p>التركيز على ما يهم فقط. عند القيادة، تحتاج لمعرفة عجلة القيادة، وليس كيفية عمل صمامات المحرك الداخلية.</p></div>\n  <div class="feature-card"><span class="f-icon">📝</span><h5>الخوارزميات</h5><p>إنشاء قائمة محددة من التعليمات خطوة بخطوة (وصفة) ليتبعها شخص ما أو الكمبيوتر.</p></div>\n</div>',
                examples: [
                    { level: 'Beginner', code: '// Problem: Making a Sandwich\n// 1. Decomposition: Get bread, get jam, spread jam.\n// 2. Patterns: Same as making any sandwich.\n// 3. Abstraction: Brand of bread doesn\'t matter.\n// 4. Algorithm: The final step-by-step guide.', desc: 'Applying computational thinking to daily tasks.', descAr: 'تطبيق التفكير الحاسوبي على المهام اليومية.' }
                ],
                why: 'Computational thinking lets you solve the logic in your head before you even touch the keyboard.',
                whyAr: 'التفكير الحاسوبي يتيح لك حل المنطق في ذهنك قبل حتى أن تلمس لوحة المفاتيح.',
                mistakes: [
                    { bad: 'Jumping straight into code', good: 'Think through the 4 pillars first', badAr: 'البدء في الكود مباشرة', goodAr: 'فكر في الركائز الأربع أولاً' }
                ],
                goodVsBad: { bad: 'Writing code without a plan.', good: 'Using decomposition to plan steps.' },
                mcqs: [
                    { q: 'Which of these is NOT one of the 4 pillars?', opts: ['Abstraction', 'Decomposition', 'Memorization', 'Algorithms'], ans: 2, fb: 'Memorization is not one of the core pillars of computational thinking.' }
                ],
                codingQs: [
                    { q: 'Write a comment showing how you would "decompose" the task of "Making Tea".', start: '// 1.\n// 2.', answer: '//' },
                    { q: 'Write a print statement that represents an "Algorithm" step for starting a car.', start: '', answer: 'print' }
                ]
            },
            {
                id: 'p1l2', title: 'How Code Runs',
                en: 'Ever wonder how a computer understands your English-like code? Computers only understand <strong>"off"</strong> and <strong>"on"</strong> (0 and 1). This is called Binary. Since writing 0s and 1s is impossible for humans, we write "Source Code" in languages like Dart, and then use a "Translator" to convert it.<br><br><strong>The Journey of Your Code:</strong>\n<div class="step-list">\n  <div class="step-item"><strong>1. Source Code</strong><p>You write instructions in Dart (Human-readable).</p></div>\n  <div class="step-item"><strong>2. Translation</strong><p>A compiler/interpreter translates Dart into zeros and ones.</p></div>\n  <div class="step-item"><strong>3. Machine Code</strong><p>The final binary code (0s and 1s) the hardware understands.</p></div>\n  <div class="step-item"><strong>4. Execution</strong><p>The CPU follows these bits to make things happen on screen.</p></div>\n</div>',
                ar: 'هل تساءلت يوماً كيف يفهم الكمبيوتر الكود الخاص بك؟ أجهزة الكمبيوتر تفهم فقط حالتي <strong>"إيقاف"</strong> و <strong>"تشغيل"</strong> (0 و 1). وهذا ما يسمى بالكود الثنائي (Binary). بما أن كتابة الأصفار والآحاد مستحيلة للبشر، فنحن نكتب "كود المصدر" بلغات مثل Dart، ثم نستخدم "مترجماً" لتحويله.<br><br><strong>رحلة الكود الخاص بك:</strong>\n<div class="step-list">\n  <div class="step-item"><strong>1. كود المصدر (Source Code)</strong><p>أنت تكتب التعليمات بلغة Dart (قابلة للقراءة للبشر).</p></div>\n  <div class="step-item"><strong>2. الترجمة (Translation)</strong><p>برنامج خاص يترجم لغة Dart إلى أصفار وآحاد.</p></div>\n  <div class="step-item"><strong>3. كود الآلة (Machine Code)</strong><p>الأصفار والآحاد النهائية التي تفهمها أجهزة الكمبيوتر.</p></div>\n  <div class="step-item"><strong>4. التنفيذ (Execution)</strong><p>يقوم المعالج باتباع هذه الأصفار والآحاد لتنفيذ المهام.</p></div>\n</div>',
                examples: [
                    { level: 'Beginner', code: '// Step 1: You write code\nprint("Hello!");\n// Step 2: Dart compiles it\n// Step 3: Machine executes binary like 01001000', desc: 'The journey from your code to the screen.', descAr: 'رحلة الكود من كتابتك إلى الشاشة.' },
                    { level: 'Intermediate', code: '// Code runs top to bottom\nprint("First");  // runs 1st\nprint("Second"); // runs 2nd', desc: 'Code executes sequentially — line by line from top to bottom.', descAr: 'الكود يُنفَّذ تسلسلياً — سطر بسطر من الأعلى للأسفل.' },
                    { level: 'Advanced', code: '// JIT vs AOT in Dart\n// JIT: Compilation during development (Fast reload).\n// AOT: Compilation for production (Fast performance).', desc: 'Dart supports multiple compilation modes for best developer experience.', descAr: 'يدعم Dart أنماط ترجمة متعددة لأفضل تجربة تطوير.' }
                ],
                why: 'Understanding this helps you appreciate why compilation errors happen—the "translator" couldn\'t understand your instructions.',
                whyAr: 'فهم هذا يساعدك على تقدير سبب حدوث أخطاء الترجمة — "المترجم" لم يستطع فهم تعليماتك.',
                mistakes: [
                    { bad: 'Thinking the CPU reads English directly', good: 'Knowing it\'s all binary at the end', badAr: 'الاعتقاد أن المعالج يقرأ الإنجليزية مباشرة', goodAr: 'معرفة أن كل شيء ينتهي بكود ثنائي' }
                ],
                goodVsBad: { bad: 'print(x); var x = 5; // Error: used before defined', good: 'var x = 5; print(x); // Success: defined before used' },
                mcqs: [
                    { q: 'Writing "print(\'Hi\');" is an example of...', opts: ['Machine code', 'Source code', 'Binary', 'CPU logic'], ans: 1, fb: 'The text you write in Dart is source code.' }
                ],
                codingQs: [
                    { q: 'Write a source code line to print "System Booting...".', start: '', answer: 'print' },
                    { q: 'Write a comment explaining what machine code looks like (zeros and ones).', start: '// ', answer: '0' }
                ]
            },
            {
                id: 'p1l3', title: 'Compiler vs Interpreter',
                en: 'Wait, there are two types of "Translators"? Yes! Compilers and Interpreters work differently, and knowing the difference is key for any developer.<br><br>\n<div class="feature-grid">\n  <div class="feature-card"><h5>📘 The Compiler</h5><p>Imagine translating a whole book before reading. It creates a ready-to-go version, making the final app <strong>very fast</strong>.</p></div>\n  <div class="feature-card"><h5>🎤 The Interpreter</h5><p>Imagine a live translator at a meeting. It translates sentence by sentence. Easier for quick changes but can be <strong>slower</strong>.</p></div>\n</div>\n<br><strong>Dart\'s Superpower:</strong> Dart 3 uses both! <strong>JIT</strong> (Interpreter) for instant development updates and <strong>AOT</strong> (Compiler) for maximum speed in the final app.',
                ar: 'انتظر، هناك نوعان من "المترجمين"؟ نعم! المترجم (Compiler) والمفسر (Interpreter) يعملان بشكل مختلف، ومعرفة الفرق هو مفتاح لأي مطور.<br><br>\n<div class="feature-grid">\n  <div class="feature-card"><h5>📘 المترجم (Compiler)</h5><p>مثل ترجمة كتاب كامل قبل البدء بقراءته. ينتج نسخة نهائية جاهزة، مما يجعل التطبيق النهائي <strong>سريعاً جداً</strong>.</p></div>\n  <div class="feature-card"><h5>🎤 المفسر (Interpreter)</h5><p>مثل المترجم الفوري في اجتماع. يترجم جملة بجملة. أسهل للتعديلات السريعة ولكن قد يكون <strong>أبطأ</strong> قليلاً.</p></div>\n</div>\n<br><strong>قوة Dart الخارقة:</strong> تستخدم Dart كليهما! <strong>JIT</strong> (المفسر) للتطوير السريع و <strong>AOT</strong> (المترجم) لأقصى سرعة في التطبيق النهائي.',
                examples: [
                    { level: 'Beginner', code: '// Compiler: Like translating a whole book first.\n// Interpreter: Like a live translator at a meeting.', desc: 'Simple analogy for understanding translation.', descAr: 'تشبيه بسيط لفهم الترجمة.' },
                    { level: 'Intermediate', code: '// Dart uses JIT for fast dev and AOT for fast apps.\n// Dev -> JIT -> Instant updates\n// Release -> AOT -> Native speed', desc: 'Dart provides the best of both worlds.', descAr: 'توفر Dart أفضل ما في العالمين.' }
                ],
                why: 'Knowing this helps you understand why Flutter development is so fast compared to traditional native development.',
                whyAr: 'معرفة هذا تساعدك على فهم سبب سرعة تطوير Flutter مقارنة بالتطوير الأصلي التقليدي.',
                mistakes: [
                    { bad: 'Thinking all languages are either one or the other', good: 'Modern languages like Dart use both for different stages', badAr: 'الاعتقاد أن كل اللغات إما هذا أو ذاك', goodAr: 'اللغات الحديثة مثل Dart تستخدم كليهما لمراحل مختلفة' }
                ],
                goodVsBad: { bad: 'Languages that need 5 mins to re-compile every change.', good: 'Dart JIT (Hot Reload) which updates in < 1 second.' },
                mcqs: [
                    { q: 'What is the main benefit of "Hot Reload"?', opts: ['Faster internet', 'Instant logic updates during dev', 'Better battery life', 'Nicer icons'], ans: 1, fb: 'Hot reload lets you see changes in < 1 second.' }
                ],
                codingQs: [
                    { q: 'Imagine you just changed a print message. How would you trigger Hot Reload (in description)?', start: '// To see changes, I use...', answer: 'Hot Reload' },
                    { q: 'Write code that you think would run faster after AOT compilation (Hint: just a print for now).', start: '', answer: 'print' }
                ]
            },
            {
                id: 'p1l4', title: 'Problem Solving Thinking',
                en: 'Programming is not about memorizing commands; it is about <strong>solving problems!</strong> Think of yourself as an architect. Before you build, you need a blueprint (a plan).<br><br><strong>The Problem-Solving Process:</strong>\n<div class="step-list">\n  <div class="step-item"><strong>1. Understand</strong><p>Read requirements twice. What is the Input? What is the Output?</p></div>\n  <div class="step-item"><strong>2. Plan</strong><p>Use your Computational Thinking tools. Break it down into steps.</p></div>\n  <div class="step-item"><strong>3. Write</strong><p>Translate your logical plan into real Dart code.</p></div>\n  <div class="step-item"><strong>4. Test & Debug</strong><p>Run your code. If it doesn\'t work, find the "bug" and fix it.</p></div>\n</div>',
                ar: 'البرمجة ليست مجرد حفظ أوامر؛ بل هي عن <strong>حل المشكلات!</strong> فكر في نفسك كمهندس معماري. قبل البناء، تحتاج إلى مخطط (خطة).<br><br><strong>عملية حل المشكلات:</strong>\n<div class="step-list">\n  <div class="step-item"><strong>1. الفهم</strong><p>اقرأ المتطلبات مرتين. ما هي المدخلات؟ وما هي المخرجات؟</p></div>\n  <div class="step-item"><strong>2. التخطيط</strong><p>استخدم أدوات التفكير الحاسوبي. قسم المشكلة إلى خطوات.</p></div>\n  <div class="step-item"><strong>3. الكتابة</strong><p>ترجم خطتك المنطقية إلى كود Dart حقيقي.</p></div>\n  <div class="step-item"><strong>4. الاختبار والتصحيح</strong><p>شغل الكود. إذا لم يعمل، ابحث عن الخطأ (الـ bug) وأصلحه.</p></div>\n</div>',
                examples: [
                    { level: 'Beginner', code: '// Problem: Check if a number is even\n// Step 1: Get the number\nvar number = 8;\n// Step 2: Check if divisible by 2\nvar isEven = number % 2 == 0;\n// Step 3: Show result\nprint("$number is even: $isEven");', desc: 'Break the problem into clear steps.', descAr: 'قسّم المشكلة إلى خطوات واضحة.' },
                    { level: 'Intermediate', code: '// Problem: Find the largest of 3 numbers\nvar a = 15, b = 27, c = 9;\nvar largest = a;\nif (b > largest) largest = b;\nif (c > largest) largest = c;\nprint("Largest: $largest");', desc: 'Compare values step by step.', descAr: 'قارن القيم خطوة بخطوة.' },
                    { level: 'Advanced', code: '// Problem: Calculate average of a list\nvar scores = [85, 92, 78, 95, 88];\nvar sum = 0;\nfor (var s in scores) {\n  sum += s;\n}\nvar avg = sum / scores.length;\nprint("Average: $avg");', desc: 'Iterate and accumulate to find the average.', descAr: 'كرر وجمّع لإيجاد المتوسط.' }
                ],
                why: 'Companies hire for problem-solving skills, not syntax knowledge. Any developer can Google syntax — but thinking clearly is priceless.',
                whyAr: 'الشركات توظف بناءً على مهارات حل المشكلات، وليس معرفة الأكواد. أي مطور يمكنه البحث عن الأكواد — لكن التفكير الواضح لا يُقدَّر بثمن.',
                mistakes: [
                    { bad: 'Jumping straight into coding without planning', good: 'Always understand the problem and plan before writing code', badAr: 'القفز مباشرة للكتابة دون تخطيط', goodAr: 'دائماً افهم المشكلة وخطّط قبل كتابة الكود' },
                    { bad: 'Trying to solve the entire problem at once', good: 'Break big problems into small, manageable steps', badAr: 'محاولة حل المشكلة كاملة دفعة واحدة', goodAr: 'قسّم المشكلات الكبيرة إلى خطوات صغيرة يمكن إدارتها' }
                ],
                goodVsBad: { bad: '// No planning, chaotic code\nvar x = a > b ? a > c ? a : c : b > c ? b : c;', good: '// Clear step-by-step approach\nvar largest = a;\nif (b > largest) largest = b;\nif (c > largest) largest = c;' },
                codingQs: [
                    { q: 'Write comments outlining steps to calculate the area of a rectangle.', start: '// Step 1:\n// Step 2:\n// Step 3:\n', answer: '//' },
                    { q: 'Implement the rectangle area calculation from your plan.', start: 'void main() {\n  \n}', answer: 'var' },
                    { q: 'Write a program that checks if a number is positive, negative, or zero.', start: 'void main() {\n  var number = -5;\n  \n}', answer: 'if' },
                    { q: 'Write a program to find the sum of numbers 1 to 5 using a loop.', start: 'void main() {\n  \n}', answer: 'for' },
                    { q: 'Write a program to check if a string is empty or not.', start: 'void main() {\n  var text = "";\n  \n}', answer: 'if' }
                ],
                mcqs: [
                    { q: 'The first step in problem solving is...', opts: ['Write code immediately', 'Understand the problem', 'Test the code', 'Deploy the app'], ans: 1, fb: 'Always understand the problem first before coding.' },
                    { q: 'Computational thinking involves...', opts: ['Memorizing code', 'Breaking problems into steps', 'Using the fastest computer', 'Writing code quickly'], ans: 1, fb: 'Computational thinking is about decomposing problems logically.' },
                    { q: '"Decomposition" in programming means...', opts: ['Deleting code', 'Breaking a problem into smaller parts', 'Compiling code', 'Running tests'], ans: 1, fb: 'Decomposition = breaking a big problem into smaller, manageable pieces.' },
                    { q: 'Before writing code, you should...', opts: ['Just start typing', 'Plan your approach', 'Search for existing code', 'Ask someone else'], ans: 1, fb: 'Planning before coding saves time and prevents bugs.' },
                    { q: 'What is debugging?', opts: ['Writing new code', 'Finding and fixing errors', 'Compiling code', 'Deploying apps'], ans: 1, fb: 'Debugging is the process of finding and fixing errors in code.' },
                    { q: 'Pattern recognition helps you...', opts: ['Memorize code', 'See similarities between problems', 'Type faster', 'Use more tools'], ans: 1, fb: 'Recognizing patterns helps you apply known solutions to new problems.' },
                    { q: 'Abstraction means...', opts: ['Making code complex', 'Focusing on important details only', 'Writing shorter code', 'Using variables'], ans: 1, fb: 'Abstraction means focusing on what matters and hiding complexity.' },
                    { q: 'Which is most important for a developer?', opts: ['Typing speed', 'Problem solving ability', 'Memorizing syntax', 'Having the latest tools'], ans: 1, fb: 'Problem solving is the #1 skill for developers.' },
                    { q: 'Testing your code ensures...', opts: ['It looks pretty', 'It works correctly', 'It runs faster', 'It uses less memory'], ans: 1, fb: 'Testing verifies that your code produces the correct output.' },
                    { q: 'A bug in code is...', opts: ['A virus', 'An error or mistake', 'A feature', 'A type of variable'], ans: 1, fb: 'A bug is an error in code that causes unexpected behavior.' }
                ]
            },
            {
                id: 'p1l5', title: 'Algorithms Concept',
                en: 'An algorithm is simply a step-by-step procedure to solve a specific problem. Think of it as a <strong>"Recipe."</strong><br><br><strong>A good algorithm must have:</strong>\n<div class="feature-grid">\n  <div class="feature-card"><h5>📥 Clear Inputs</h5><p>What do you need to start (e.g., eggs, flour)?</p></div>\n  <div class="feature-card"><h5>🛤️ Clear Steps</h5><p>Logical, unambiguous instructions: "Do this, then do that."</p></div>\n  <div class="feature-card"><h5>🏁 A Finite End</h5><p>An algorithm cannot go on forever; it must eventually stop.</p></div>\n  <div class="feature-card"><h5>🍰 Correct Output</h5><p>It must result in the right answer (the finished cake!).</p></div>\n</div>',
                ar: 'الخوارزمية هي مجرد إجراء خطوة بخطوة لحل مشكلة معينة. فكر فيها كـ <strong>"وصفة طعام"</strong>.<br><br><strong>يجب أن تحتوي الخوارزمية الجيدة على:</strong>\n<div class="feature-grid">\n  <div class="feature-card"><h5>📥 مدخلات واضحة</h5><p>ماذا تحتاج للبدء (مثلاً: بيض، دقيق)؟</p></div>\n  <div class="feature-card"><h5>🛤️ خطوات واضحة</h5><p>تعليمات منطقية وغير غامضة: "افعل هذا، ثم افعل ذاك".</p></div>\n  <div class="feature-card"><h5>🏁 نهاية محددة</h5><p>الخوارزمية لا يمكن أن تستمر للأبد؛ يجب أن تكتمل في النهاية.</p></div>\n  <div class="feature-card"><h5>🍰 مخرجات صحيحة</h5><p>يجب أن تؤدي إلى النتيجة الصحيحة (الكيكة النهائية!).</p></div>\n</div>',
                examples: [
                    { level: 'Beginner', code: '// Algorithm: Make tea\n// 1. Boil water\n// 2. Put tea bag in cup\n// 3. Pour hot water\n// 4. Wait 3 minutes\n// 5. Remove tea bag\n// 6. Enjoy!', desc: 'A real-world algorithm with clear steps.', descAr: 'خوارزمية واقعية بخطوات واضحة.' },
                    { level: 'Intermediate', code: '// Algorithm: Find maximum in a list\nvar numbers = [4, 9, 2, 7, 5];\nvar max = numbers[0];\nfor (var n in numbers) {\n  if (n > max) max = n;\n}\nprint("Maximum: $max"); // 9', desc: 'A simple search algorithm.', descAr: 'خوارزمية بحث بسيطة.' },
                    { level: 'Advanced', code: '// Algorithm: Linear search\nvar items = ["apple","banana","cherry"];\nvar target = "banana";\nvar found = false;\nfor (var i = 0; i < items.length; i++) {\n  if (items[i] == target) {\n    print("Found at index $i");\n    found = true;\n    break;\n  }\n}\nif (!found) print("Not found");', desc: 'Searching through data systematically.', descAr: 'البحث في البيانات بشكل منهجي.' }
                ],
                why: 'Algorithms are the backbone of all software — from search engines to social media feeds. Understanding them makes you a better developer.',
                whyAr: 'الخوارزميات هي العمود الفقري لكل البرمجيات — من محركات البحث إلى وسائل التواصل الاجتماعي.',
                mistakes: [{ bad: 'Making an algorithm with infinite steps or unclear logic', good: 'Every algorithm must eventually end and produce a result', badAr: 'كتابة خوارزمية بخطوات لا نهائية أو منطق غير واضح', goodAr: 'كل خوارزمية يجب أن تنتهي في النهاية وتنتج نتيجة' }, { bad: 'Skipping edge cases', good: 'Consider what happens with empty lists, negative numbers, etc.', badAr: 'تجاهل الحالات الحدية', goodAr: 'فكّر فيما يحدث مع قوائم فارغة، أرقام سالبة، إلخ' }],
                goodVsBad: { bad: '// No clear structure\nif(x>y){if(x>z){r=x;}else{r=z;}}else{if(y>z){r=y;}else{r=z;}}', good: '// Clear algorithmic steps\nvar result = x;\nif (y > result) result = y;\nif (z > result) result = z;' },
                codingQs: [{ q: 'Write an algorithm in comments to calculate the sum of all numbers from 1 to 10.', start: '// Algorithm:\n', answer: '//' }, { q: 'Implement the sum algorithm from the previous question.', start: 'void main() {\n  \n}', answer: 'for' }, { q: 'Write a program to find the minimum value in a list [8, 3, 9, 1, 6].', start: 'void main() {\n  var nums = [8, 3, 9, 1, 6];\n  \n}', answer: 'for' }, { q: 'Write a program that counts how many even numbers are in [1,2,3,4,5,6,7,8].', start: 'void main() {\n  \n}', answer: 'for' }, { q: 'Write a search algorithm that finds if "dart" exists in a list of languages.', start: 'void main() {\n  var langs = ["python","dart","java"];\n  \n}', answer: 'for' }],
                mcqs: [{ q: 'An algorithm is...', opts: ['A programming language', 'A step-by-step procedure', 'A type of variable', 'A compiler'], ans: 1, fb: 'An algorithm is a step-by-step procedure to solve a problem.' }, { q: 'A good algorithm must be...', opts: ['Infinite', 'Finite and produce correct results', 'Very long', 'Written in English'], ans: 1, fb: 'Algorithms must be finite, unambiguous, and produce correct output.' }, { q: 'The word "algorithm" comes from...', opts: ['Albert Einstein', 'Al-Khwarizmi', 'Alan Turing', 'Ada Lovelace'], ans: 1, fb: 'Named after the Persian mathematician Al-Khwarizmi.' }, { q: 'Which is an example of a real-world algorithm?', opts: ['A recipe', 'A painting', 'A song', 'A dream'], ans: 0, fb: 'A recipe has clear inputs, steps, and output — just like an algorithm.' }, { q: 'Linear search checks elements...', opts: ['All at once', 'One by one from start', 'From the middle', 'Randomly'], ans: 1, fb: 'Linear search checks each element sequentially from the beginning.' }, { q: 'An algorithm must have...', opts: ['A GUI', 'Input and output', 'Colors', 'Internet'], ans: 1, fb: 'Algorithms have defined inputs, a process, and outputs.' }, { q: 'What is a "step" in an algorithm?', opts: ['A single clear instruction', 'A whole program', 'A paragraph of text', 'A variable'], ans: 0, fb: 'Each step is one clear, actionable instruction.' }, { q: 'Finding the largest number in a list is...', opts: ['Impossible', 'A search algorithm', 'A sort algorithm', 'Not an algorithm'], ans: 1, fb: 'It\'s a search/comparison algorithm.' }, { q: '"Sorting" means...', opts: ['Deleting items', 'Arranging items in order', 'Counting items', 'Copying items'], ans: 1, fb: 'Sorting = arranging items in a specific order.' }, { q: 'Efficiency in algorithms means...', opts: ['Writing less code', 'Solving the problem with fewer steps/resources', 'Using more variables', 'Making it look nice'], ans: 1, fb: 'Efficient algorithms use minimal time and resources.' }]
            },
            {
                id: 'p1l6', title: 'Pseudocode Basics',
                en: 'Pseudocode (pronounced <i>"Soo-doe-code"</i>) is <strong>"Fake Code."</strong> It is a way to plan your program using plain English without worrying about strict syntax rules.<br><br><strong>Why use Pseudocode?</strong>\n<div class="feature-grid">\n  <div class="feature-card"><h5>🧠 Logic First</h5><p>Focus on <strong>How</strong> to solve the problem, not what symbol or semicolon to use.</p></div>\n  <div class="feature-card"><h5>🤝 Easy to Share</h5><p>Anyone can understand your logic, even if they don\'t know the Dart language.</p></div>\n  <div class="feature-card"><h5>🗺️ Easy Translation</h5><p>Once your plan is right, converting it to real code is like following a map.</p></div>\n</div>',
                ar: 'الكود الزائف (Pseudocode) هو <strong>"كود وهمي"</strong>. هو طريقة لتخطيط برنامجك باستخدام لغة بسيطة دون القلق بشأن قواعد البرمجة الصارمة.<br><br><strong>لماذا نستخدم الكود الزائف؟</strong>\n<div class="feature-grid">\n  <div class="feature-card"><h5>🧠 المنطق أولاً</h5><p>التركيز على <strong>كيفية</strong> الحل، وليس على الرموز أو الفواصل المنقوطة.</p></div>\n  <div class="feature-card"><h5>🤝 سهولة المشاركة</h5><p>يمكن لأي شخص فهم منطقك، حتى لو لم يكن يعرف لغة Dart.</p></div>\n  <div class="feature-card"><h5>🗺️ سهولة الترجمة</h5><p>بمجرد أن يكون المخطط صحيحاً، فإن تحويله لكود حقيقي يصبح أمراً سهلاً.</p></div>\n</div>',
                examples: [
                    { level: 'Beginner', code: '// Pseudocode:\n// START\n//   SET name = "Ahmed"\n//   PRINT "Hello " + name\n// END\n\n// Dart:\nvoid main() {\n  var name = "Ahmed";\n  print("Hello $name");\n}', desc: 'Pseudocode → Dart translation.', descAr: 'ترجمة الكود الزائف إلى Dart.' },
                    { level: 'Intermediate', code: '// Pseudocode:\n// READ number\n// IF number > 0 THEN\n//   PRINT "Positive"\n// ELSE IF number < 0 THEN\n//   PRINT "Negative"\n// ELSE\n//   PRINT "Zero"\n// END IF\n\nvoid main() {\n  var number = -3;\n  if (number > 0) print("Positive");\n  else if (number < 0) print("Negative");\n  else print("Zero");\n}', desc: 'Decision-making in pseudocode and Dart.', descAr: 'اتخاذ القرارات بالكود الزائف وDart.' },
                    { level: 'Advanced', code: '// Pseudocode:\n// SET sum = 0\n// FOR i FROM 1 TO 10\n//   sum = sum + i\n// END FOR\n// PRINT sum\n\nvoid main() {\n  var sum = 0;\n  for (var i = 1; i <= 10; i++) {\n    sum += i;\n  }\n  print("Sum: $sum"); // 55\n}', desc: 'Loop logic in pseudocode then real code.', descAr: 'منطق التكرار بالكود الزائف ثم الكود الحقيقي.' }
                ],
                why: 'Professional developers often sketch pseudocode on whiteboards before coding. It saves hours of debugging and ensures your logic is sound.',
                whyAr: 'المطورون المحترفون غالباً يرسمون الكود الزائف على السبورة قبل البرمجة. يوفر ساعات من التصحيح ويضمن سلامة المنطق.',
                mistakes: [{ bad: 'Writing pseudocode that is too detailed (like real code)', good: 'Keep pseudocode simple and focused on logic, not syntax', badAr: 'كتابة كود زائف مفصّل جداً (مثل الكود الحقيقي)', goodAr: 'اجعل الكود الزائف بسيطاً ومركّزاً على المنطق' }, { bad: 'Skipping pseudocode and jumping into coding', good: 'Plan with pseudocode first, especially for complex problems', badAr: 'تخطي الكود الزائف والقفز للبرمجة مباشرة', goodAr: 'خطّط بالكود الزائف أولاً، خصوصاً للمشكلات المعقدة' }],
                goodVsBad: { bad: '// No planning, confusing logic\nfor(var i=0;i<n;i++){if(arr[i]>m){m=arr[i];}if(arr[i]<mn){mn=arr[i];}}', good: '// Pseudocode first:\n// FOR each number in list\n//   IF number > max THEN max = number\n//   IF number < min THEN min = number\n// END FOR' },
                codingQs: [{ q: 'Write pseudocode as comments for finding the average of 4 numbers.', start: '// Pseudocode:\n', answer: '//' }, { q: 'Convert your pseudocode into a working Dart program.', start: 'void main() {\n  \n}', answer: 'var' }, { q: 'Write pseudocode plus Dart code for checking if someone can vote (age >= 18).', start: '// Pseudocode:\n// \n\nvoid main() {\n  \n}', answer: 'if' }, { q: 'Write pseudocode for counting backwards from 10 to 1.', start: '// Pseudocode:\n', answer: '//' }, { q: 'Convert the countdown pseudocode to Dart with a for loop.', start: 'void main() {\n  \n}', answer: 'for' }],
                mcqs: [{ q: 'Pseudocode is...', opts: ['A programming language', 'Plain English code planning', 'A type of variable', 'A compiler'], ans: 1, fb: 'Pseudocode is a plain-language way to plan your program logic.' }, { q: 'Pseudocode focuses on...', opts: ['Syntax', 'Logic', 'Design', 'Testing'], ans: 1, fb: 'Pseudocode prioritizes logic over language-specific syntax.' }, { q: 'Which is valid pseudocode?', opts: ['void main() {}', 'IF age > 18 THEN PRINT "Adult"', 'console.log("hi")', '#include <stdio.h>'], ans: 1, fb: 'Pseudocode uses plain words like IF, THEN, PRINT.' }, { q: 'When should you write pseudocode?', opts: ['After coding', 'Before coding', 'Never', 'Only for big projects'], ans: 1, fb: 'Write pseudocode before coding to plan your logic.' }, { q: 'Pseudocode is written in...', opts: ['Only English', 'Only Arabic', 'Any language', 'Only Dart'], ans: 2, fb: 'Pseudocode can be written in any language you think in.' }, { q: 'What does "WHILE condition DO" mean in pseudocode?', opts: ['Define a function', 'Repeat while condition is true', 'Create a variable', 'Print output'], ans: 1, fb: 'WHILE loops repeat as long as the condition remains true.' }, { q: 'Pseudocode must follow strict syntax rules.', opts: ['True', 'False'], ans: 1, fb: 'Pseudocode has no strict syntax — it\'s flexible and informal.' }, { q: 'Why is pseudocode helpful?', opts: ['It runs faster', 'It helps plan logic before syntax', 'It replaces testing', 'It looks cooler'], ans: 1, fb: 'It separates thinking about logic from worrying about syntax.' }, { q: 'A flowchart is...', opts: ['A type of pseudocode', 'A visual diagram of an algorithm', 'A programming language', 'A testing tool'], ans: 1, fb: 'Flowcharts are visual representations of algorithms.' }, { q: 'START and END in pseudocode indicate...', opts: ['Variables', 'The beginning and end of the program', 'Functions', 'Loops'], ans: 1, fb: 'START and END mark the boundaries of the program flow.' }]
            }
        ]
    },
    {
        id: 'p2', title: 'Phase 2 — Dart Introduction', lessons: [
            {
                id: 'p2l1', title: 'What is Dart',
                en: 'Dart is a modern programming language created by Google. Think of it as the <strong>"Language of the Future"</strong> for building apps.<br><br><strong>Why choose Dart?</strong>\n<div class="feature-grid">\n  <div class="feature-card"><h5>📱 Flutter Ready</h5><p>The secret ingredient behind Flutter. Build for iOS, Android, and Web from one codebase.</p></div>\n  <div class="feature-card"><h5>⚡ Fast & Productive</h5><p>Designed to be easy for humans to read but incredibly fast for computers to run.</p></div>\n  <div class="feature-card"><h5>🛡️ Type Safe</h5><p>Helps you catch errors early with a strong type system and modern features like Null Safety.</p></div>\n</div>',
                ar: 'لغة Dart هي لغة برمجة حديثة أنشأتها شركة Google. فكر فيها على أنها <strong>"لغة المستقبل"</strong> لبناء التطبيقات.<br><br><strong>لماذا تختار Dart؟</strong>\n<div class="feature-grid">\n  <div class="feature-card"><h5>📱 جاهزة لـ Flutter</h5><p>المكون السري وراء Flutter. ابني لـ iOS و Android والويب من كود واحد.</p></div>\n  <div class="feature-card"><h5>⚡ سريعة ومنتجة</h5><p>مصممة لتكون سهلة القراءة للبشر وسريعة جداً في التنفيذ للكمبيوتر.</p></div>\n  <div class="feature-card"><h5>🛡️ أمان الأنواع</h5><p>تساعدك على اكتشاف الأخطاء مبكراً بفضل نظام الأنواع القوي وميزات مثل Null Safety.</p></div>\n</div>',
                examples: [
                    { level: 'Beginner', code: 'void main() {\n  print("Hello Dart! 🎯");\n}', desc: 'Your first Dart program.', descAr: 'أول برنامج لك بلغة Dart.' },
                    { level: 'Intermediate', code: 'void main() {\n  String language = "Dart";\n  int year = 2011;\n  print("$language was created in $year");\n  print("Made by Google");\n}', desc: 'Using variables and string interpolation.', descAr: 'استخدام المتغيرات ودمج النصوص.' },
                    { level: 'Advanced', code: 'void main() {\n  var features = [\n    "Type safe",\n    "Null safety",\n    "Async/await",\n    "OOP",\n    "Fast compilation"\n  ];\n  print("Dart features:");\n  for (var f in features) {\n    print("  ✓ $f");\n  }\n}', desc: 'Lists and loops in Dart.', descAr: 'القوائم والتكرار في Dart.' }
                ],
                why: 'Dart is your gateway to Flutter. Mastering Dart means you can build apps for iOS, Android, web, and desktop — all from one language.',
                whyAr: 'Dart هو بوابتك إلى Flutter. إتقان Dart يعني أنك تستطيع بناء تطبيقات لـ iOS وAndroid والويب وسطح المكتب — كلها بلغة واحدة.',
                mistakes: [{ bad: 'Thinking Dart is only for Flutter', good: 'Dart can be used for CLI tools, servers, and web apps too', badAr: 'الاعتقاد أن Dart فقط لـ Flutter', goodAr: 'Dart يمكن استخدامه لأدوات سطر الأوامر والسيرفرات وتطبيقات الويب أيضاً' }, { bad: 'Comparing Dart negatively to other languages', good: 'Every language has strengths — Dart excels in UI and cross-platform development', badAr: 'مقارنة Dart سلبياً بلغات أخرى', goodAr: 'كل لغة لها نقاط قوة — Dart يتفوق في واجهات المستخدم والتطوير متعدد المنصات' }],
                goodVsBad: { bad: '// Not using Dart features\nvar x = "Hello" + " " + name + "!";', good: '// Using string interpolation\nvar greeting = "Hello $name!";' },
                codingQs: [{ q: 'Write a Dart program that prints "I am learning Dart!".', start: 'void main() {\n  \n}', answer: 'print' }, { q: 'Create a variable with your name and print a greeting.', start: 'void main() {\n  \n}', answer: 'var' }, { q: 'Print 3 facts about Dart as a language.', start: 'void main() {\n  \n}', answer: 'print' }, { q: 'Create a list of 3 programming languages and print them.', start: 'void main() {\n  \n}', answer: 'var' }, { q: 'Write a program using string interpolation to display your age.', start: 'void main() {\n  \n}', answer: '$' }],
                mcqs: [{ q: 'Dart was created by...', opts: ['Apple', 'Microsoft', 'Google', 'Facebook'], ans: 2, fb: 'Dart was created by Google in 2011.' }, { q: 'Dart is...', opts: ['A framework', 'A programming language', 'An IDE', 'A database'], ans: 1, fb: 'Dart is a programming language.' }, { q: 'Dart was first released in...', opts: ['2005', '2011', '2017', '2020'], ans: 1, fb: 'Dart was first released in 2011.' }, { q: 'Dart is used with...', opts: ['React', 'Angular only', 'Flutter', 'Swift'], ans: 2, fb: 'Dart is the language used with Flutter.' }, { q: 'String interpolation in Dart uses...', opts: ['+ operator only', '$variable or ${expression}', '% operator', 'f-strings'], ans: 1, fb: 'Dart uses $variable or ${expression} for string interpolation.' }, { q: 'Dart supports which platforms?', opts: ['Mobile only', 'Web only', 'Mobile, web, and desktop', 'Desktop only'], ans: 2, fb: 'Dart supports mobile, web, and desktop platforms.' }, { q: 'The entry point of a Dart program is...', opts: ['start()', 'init()', 'main()', 'run()'], ans: 2, fb: 'Every Dart program starts executing from main().' }, { q: 'Dart is...', opts: ['Dynamically typed only', 'Statically typed', 'Not typed', 'Weekly typed'], ans: 1, fb: 'Dart is statically typed with type inference.' }, { q: 'Dart compiles to...', opts: ['Only JavaScript', 'Only machine code', 'JavaScript, machine code, or bytecode', 'Only bytecode'], ans: 2, fb: 'Dart can compile to multiple targets.' }, { q: 'To print in Dart, you use...', opts: ['console.log()', 'System.out.println()', 'print()', 'echo()'], ans: 2, fb: 'Dart uses print() to output to the console.' }]
            }
        ]
    }
];
